"""Prepare a disposable source checkout for a static Studio preview build."""
import datetime
import json
import os
import pathlib
import re
import shutil
import subprocess
import sys


def prepare(source, sha):
    source = pathlib.Path(source).resolve()
    if not re.fullmatch('[a-f0-9]{40}', sha):
        raise ValueError('invalid source SHA')
    actual = subprocess.check_output(['git', '-C', str(source), 'rev-parse', 'HEAD'], text=True).strip()
    if actual != sha:
        raise ValueError('checkout SHA mismatch')
    studio = source / 'rhwp-studio'
    # A separate public directory prevents sample symlinks/corpora from being copied.
    public = studio / '.preview-public'
    if public.exists():
        raise ValueError('preview public directory already exists')
    public.mkdir()
    for entry in (studio / 'public').iterdir():
        if entry.name == 'samples':
            continue
        if entry.is_symlink():
            # This repository intentionally exposes its distributable font assets
            # through public/fonts. Never follow arbitrary checkout symlinks.
            target = entry.resolve()
            if entry.name != 'fonts' or target != (source/'assets/fonts').resolve() or not target.is_relative_to(source):
                continue
            entry = target
        if entry.is_dir():
            shutil.copytree(entry, public / entry.name, ignore=lambda path, names: [n for n in names if (pathlib.Path(path)/n).is_symlink()])
        else:
            shutil.copyfile(entry, public / entry.name)
    config = """import config from './vite.config';
export default {...config, base:'/', publicDir:'.preview-public',
  plugins:config.plugins.flat().filter(p=>!p.name.startsWith('vite-plugin-pwa'))};
"""
    (studio / 'vite.preview.config.ts').write_text(config)


def stamp(source, sha):
    dist = pathlib.Path(source) / 'rhwp-studio/dist'
    metadata = {'sha': sha, 'run_id': os.environ['GITHUB_RUN_ID'], 'attempt': os.environ['GITHUB_RUN_ATTEMPT'],
                'built_at': datetime.datetime.now(datetime.timezone.utc).isoformat(), 'profile': 'release', 'pwa': False}
    (dist / 'build.json').write_text(json.dumps(metadata))
    # Visible provenance is generated by the build harness, not inferred from cached UI.
    index = dist / 'index.html'
    text = index.read_text()
    banner = f'<aside style="position:fixed;bottom:0;right:0;z-index:2147483647;background:#132235;color:white;font:11px monospace;padding:4px" aria-label="Preview build">Preview {sha} · {metadata["built_at"]}</aside>'
    if '</body>' not in text:
        raise ValueError('missing HTML body')
    index.write_text(text.replace('</body>', banner + '</body>'))


if __name__ == '__main__':
    if sys.argv[1] == 'prepare':
        prepare(sys.argv[2], sys.argv[3])
    elif sys.argv[1] == 'stamp':
        stamp(sys.argv[2], sys.argv[3])
    else:
        raise ValueError('unknown operation')
